#!/usr/bin/env ash

set -e

main() {
  mkdir -p /home/builder/packages /home/builder/.abuild
  abuild-apk update
  [ "$RSA_PRIVATE_KEY" ] && {
    echo -n "$RSA_PRIVATE_KEY" | base64 -di > "/home/builder/$RSA_PRIVATE_KEY_NAME"
    export PACKAGER_PRIVKEY="/home/builder/$RSA_PRIVATE_KEY_NAME"
  }

  exec abuild "$@"
}

main "$@"
